export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const GET_NAVBARMENU = "GET_NAVBARMENU";

export const GET_TEST_PACKAGE_TYPES_SUCCESS = "GET_TEST_PACKAGE_TYPES_SUCCESS";
export const GET_TEST_PACKAGE_TYPES_FAIL = "GET_TEST_PACKAGE_TYPES_FAIL";
export const TEST_TYPE_PACKAGE_INSERT_SUCCESS =
  "TEST_TYPE_PACKAGE_INSERT_SUCCESS";
export const TEST_TYPE_PACKAGE_INSERT_FAIL = "TEST_TYPE_PACKAGE_INSERT_FAIL";

export const GET_TEST_PACKAGE_SUCCESS = "GET_TEST_PACKAGE_SUCCESS";
export const GET_TEST_PACKAGE_FAIL = "GET_TEST_PACKAGE_FAIL";
export const TEST_PACKAGE_INSERT_SUCCESS = "TEST_PACKAGE_INSERT_SUCCESS";
export const TEST_PACKAGE_INSERT_FAIL = "TEST_PACKAGE_INSERT_FAIL";

export const SELECTED_TEST_TYPE = "SELECTED_TEST_TYPE";
